name: Security and Quality Checks

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run security audit
      run: |
        npm audit --audit-level moderate
        npm audit --audit-level high --dry-run || true
    
    - name: Check for outdated packages
      run: npm outdated || true

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Lint JavaScript
      run: |
        # Basic syntax checking
        node -c server.js
        node -c script.js
    
    - name: Check for potential issues
      run: |
        echo "Checking for common security issues..."
        # Check for hardcoded secrets (basic check)
        grep -r "sk_live\|pk_live" . --exclude-dir=node_modules || echo "No live keys found"
        # Check for console.log statements that might expose data
        grep -r "console.log" . --exclude-dir=node_modules --exclude="*.md" || echo "Console logs found - review for sensitive data"

  test-build:
    name: Test Build Process
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Test server startup
      run: |
        timeout 10s npm start || echo "Server start test completed"
    
    - name: Validate package.json
      run: npm ls --depth=0