name: Security Analysis

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    # Run weekly on Sundays at 3 AM UTC
    - cron: '0 3 * * 0'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' || github.repository == github.event.repository.full_name
    
    strategy:
      matrix:
        language: [ 'javascript' ]
        
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3.26.12
      with:
        languages: ${{ matrix.language }}
        
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3.26.12
      with:
        category: "/language:${{matrix.language}}"

  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    # Only run on pull requests for public repositories or private repositories with GitHub Advanced Security
    if: github.event_name == 'pull_request' && (github.repository_visibility == 'public' || github.event.repository.private == false)
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      
    - name: Dependency Review
      uses: actions/dependency-review-action@v4.4.0
      with:
        fail-on-severity: moderate
        
  audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.7
      
    - name: Setup Node.js
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '18.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run security audit
      run: npm audit --audit-level moderate